### ISSUE TITLE
MAC addresses are considered as different interfaces if they are uppercase or lowercase

### ISSUE THREAD

**Issue by rogerpueyo** [libremap/libremap-agent-openwrt#13]
Links between qMp nodes are not shown in Libremap (see for instancehttp://libremap.net/#bbox/41.32381345581024,2.0822417736053467,41.33096789744496,2.097691297531128). In this area, nodes http://libremap.net/api/router/43606c1dda7bb9f887b3b624c0189927 and http://libremap.net/api/router/bfae24c7abc7f08144fb146717b2700d are linked but the map does not show so.

I've seen that if I force MAC addresses to be published in uppercase (see nodes in area http://libremap.net/#bbox/41.37529501839182,2.161785364151001,41.38244380449015,2.1772348880767822) links magically appear on the map. I guess that libremap-agent should consistently publish all MAC addresses either in uppercase or lowercase, but also libremap api should treat MAC addresses as case insensitive strings.

Thanks!

**Comment by andrenarchy** [comment]
Thanks for your PR #14! I think that the alias should be handled by the plugin. Which plugin are you using?

**Comment by rogerpueyo** [comment]
I am using libremap-agent in qMp (an OpenWrt-based firmware for mesh networking). It was not included by me though, so I am not really familiar with libremap and I am not sure of what is the plugin. Anyway, shouldn't the web treat MAC addresses as case insensitive? :)

**Comment by andrenarchy** [comment]
You're absolutely right: mac addresses should be treated case insensitive. However, the alias may not be a mac address but some other identifier (which may be case sensitive). The proper way to treat this is to adapt the [wireless plugin](https://github.com/libremap/libremap-agent-openwrt/blob/master/libremap-agent/luasrc/libremap/plugins/wireless.lua) such that mac addresses are converted to lower case (I guess most linux tools spit them out in lower case). Do you want to prepare a new PR?

**Comment by rogerpueyo** [comment]
Please see PR https://github.com/libremap/libremap-agent-openwrt/pull/16

**Comment by andrenarchy** [comment]
Fixed in #16
