### ISSUE TITLE
libremap-agent fails due to missing luci.fs dependency

### ISSUE THREAD

**Issue by rogerpueyo** [libremap/libremap-agent-openwrt#15]
Hi,

libremap-agent fails to run on recent compilations of the package:

    root@openwrt:~# /usr/sbin/libremap-agent 
    /usr/bin/lua: module 'luci.fs' not found:
    	no field package.preload['luci.fs']
    	no file './luci/fs.lua'
    	no file '/usr/share/lua/luci/fs.lua'
    	no file '/usr/share/lua/luci/fs/init.lua'
    	no file '/usr/lib/lua/luci/fs.lua'
    	no file '/usr/lib/lua/luci/fs/init.lua'
    	no file './luci/fs.so'
    	no file '/usr/lib/lua/luci/fs.so'
    	no file '/usr/lib/lua/loadall.so'
    	no file './luci.so'
    	no file '/usr/lib/lua/luci.so'
    	no file '/usr/lib/lua/loadall.so'
    stack traceback:
    	[C]: in function 'require'
    	?: in main chunk
    	[C]: in function 'require'
    	/usr/sbin/libremap-agent:4: in main chunk
    	[C]: ?    

The file was dropped from LuCI on the 15th January 2015 (https://github.com/openwrt/luci/commit/e91b603acc0920f998ae57704a9d97b83ee284e4).

Maybe it could be added to libremap-agent package.

**Comment by rogerpueyo** [comment]
Please see pull request 16

**Comment by andrenarchy** [comment]
fixed with #16
